version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    volumes:
      - .:/var/www
    depends_on:
      - database
      - elasticsearch

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fastcgi-php.conf:/etc/nginx/conf.d/fastcgi-php.conf 
    depends_on:
      - app

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_moho_kala
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
    depends_on:
      - database

  elasticsearch:
    image: elasticsearch:8.4.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data

  js:
    image: node:18
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 5173:5173
    command: ["npm", "run", "dev"]
    depends_on:
      - app

volumes:
  db_data: ~
  es_data: ~
